debug = false
logLevel = "ERROR"
defaultEntryPoints = ["http", "https"]

[entryPoints]
 [entryPoints.http]
 address = ":80"
   [entryPoints.http.redirect]
   entryPoint = "https"
  [entryPoints.https]
 address = ":443"
  [entryPoints.https.auth.basic]
  users = ["test1:$apr1$YTy3zdNs$WrNXk4SqKbIK7hBgzB8U3/"]
    [entryPoints.https.tls]

[acme]
email = "abhishek.soni@cuelogic.com"
storage = "/etc/traefik/acme/acme.json"
entryPoint = "https"
onHostRule = true

[[acme.domains]]
 main = "cueops.io"
 sans = ["jenkins-lessonbee.cueops.io", "nexus-lessonbee.cueops.io", "stackstorm-lessonbee.cueops.io"]

[web]
address = ":8080"

[web.auth.basic]
    users = ["traefik:$apr1$M5eALESf$daca0RpyLab9SWfRyt0Ot0"]


[docker]
domain = "cueops.io"
watch = true
swarmmode = true
exposedbydefault = false
